frontend:
  replicaCount: 1
  image:
    repository: juan12311/frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  replicaCount: 1
  image:
    repository: juan12311/backend
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    dbHost: "{{ .Release.Name }}-postgresql"
    dbPort: "5432"
    dbName: "pedidos"

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
  auth:
    username: "postgres"
    password: "password"
    database: "pedidos"
  primary:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "pedido-app.local"
