frontend:
  replicaCount: 1
  image:
    tag: "lastest"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  replicaCount: 1
  image:
    tag: "lastest"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

postgresql:
  auth:
    username: "postgres"
    password: "devpassword"
    database: "pedidos"

ingress:
  hosts:
    - host: "dev.pedido-app.local"
