frontend:
  replicaCount: 3
  image:
    tag: "latest"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

backend:
  replicaCount: 3
  image:
    tag: "latest"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

postgresql:
  auth:
    username: "postgres"
    password: "prodpassword"
    database: "pedidos_prod"
