apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pedido-app.fullname" . }}-backend-secret
  labels:
    app.kubernetes.io/component: backend
    {{- include "pedido-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
