server {
    listen       80;
    server_name  localhost;

    charset utf-8;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el Backend Django cuando accedemos al frontend mediante Localhost (evitando bloqueos del Ingress)
    location /pedidos/api/ {
        proxy_pass http://pedido-dev-test-pedido-app-backend:8000/pedidos/api/;
        proxy_set_header Host $host;
    }

    # error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
