apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pedido-app.fullname" . }}-frontend-config
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        charset utf-8;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /pedidos/api/ {
            proxy_pass http://{{ include "pedido-app.fullname" . }}-backend:8000/pedidos/api/;
            proxy_set_header Host $host;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
