apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-dev
  namespace: argocd
spec:
  project: default
  source:
    # URL del repositorio Git donde se encuentra el chart y los values
    repoURL: 'https://github.com/storresp/pedidos-app.git' # Reemplazar con URL real
    targetRevision: juandi
    path: charts/pedido-app
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
